# Generated by Django 4.2.10 on 2024-02-15 06:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zango.apps.dynamic_models.fields
from ..utils import DefaultConfigKeyMixin
import zango.core.storage_utils


def create_default_active_status(apps, schema_editor):
    CommmunicationActiveModel = apps.get_model(
        "dynamic_models", "CommmunicationActiveModel"
    )
    CommmunicationActiveModel.objects.create()


class Migration(migrations.Migration):
    dependencies = [
        ("appauth", "0006_appusermodel_app_objects"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key", models.CharField(blank=True, max_length=100, unique=True)),
                ("from_email", models.EmailField(max_length=254)),
                ("provider", models.CharField(default="basic", max_length=100)),
                ("provider_package_name", models.CharField(blank=True, max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        null=True, verbose_name="Config"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                DefaultConfigKeyMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MeetingHostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("host_name", models.CharField(max_length=50, null=True)),
                (
                    "host_object_uuid",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("host_email", models.EmailField(max_length=254, null=True)),
                (
                    "provider_config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True, verbose_name="Provider config"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SmsConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "icon",
                    zango.core.storage_utils.ZFileField(
                        blank=True,
                        null=True,
                        upload_to=zango.core.storage_utils.RandomUniqueFileName,
                        validators=[zango.core.storage_utils.validate_file_extension],
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("provider_package_name", models.CharField(max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Config"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                DefaultConfigKeyMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VideoCallConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key", models.CharField(blank=True, max_length=25, unique=True)),
                ("provider", models.CharField(max_length=25, verbose_name="Provider")),
                ("provider_package_name", models.CharField(max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Config"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                DefaultConfigKeyMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VideoCallRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key", models.CharField(blank=True, max_length=25, unique=True)),
                ("room_id", models.CharField(blank=True, max_length=100)),
                (
                    "participants",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True, verbose_name="Participants"
                    ),
                ),
                (
                    "meeting_details",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True, verbose_name="Meeting details"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(null=True, verbose_name="Scheduled Time"),
                ),
                (
                    "start_time",
                    models.DateTimeField(null=True, verbose_name="Start Time"),
                ),
                ("end_time", models.DateTimeField(null=True, verbose_name="End Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("scheduled", "Scheduled"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "call_recording_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Video Call Record URL"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "meeting_host",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynamic_models.meetinghostmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "videocall_config",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videocall_config",
                        to="dynamic_models.videocallconfigmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                DefaultConfigKeyMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TelephonyConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "icon",
                    zango.core.storage_utils.ZFileField(
                        blank=True,
                        null=True,
                        upload_to=zango.core.storage_utils.RandomUniqueFileName,
                        validators=[zango.core.storage_utils.validate_file_extension],
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("provider_package_name", models.CharField(max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Config"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                DefaultConfigKeyMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TelephonyAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("provider", models.CharField(max_length=100)),
                ("provider_package_name", models.CharField(max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Config"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "user",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SMSTransactionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "to_number",
                    models.CharField(
                        max_length=20, verbose_name="Recipient Phone Number"
                    ),
                ),
                (
                    "src",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Source Mobile Number"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "date_sent",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Sent"),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                (
                    "provider",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Response Code"
                    ),
                ),
                (
                    "response_text",
                    models.TextField(null=True, verbose_name="Response Text"),
                ),
                (
                    "delivery_exception",
                    models.TextField(null=True, verbose_name="Delivery Exception"),
                ),
                (
                    "config",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dynamic_models.smsconfigmodel",
                        verbose_name="Config",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Message ID"
                    ),
                ),
                ("from_email", models.EmailField(max_length=254)),
                (
                    "to_email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "cc_email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "bcc_email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("IN", "Inbound"),
                            ("OUT", "Outbound"),
                            ("DR", "Draft"),
                        ],
                        default="DR",
                        max_length=3,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("service_inactive", "Service Inactive"),
                            ("received", "Received"),
                        ],
                        default="staged",
                        max_length=20,
                    ),
                ),
                (
                    "send_responses",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                ("send_attempt_number", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "mail_config",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynamic_models.emailconfigmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "owner",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file",
                    zango.core.storage_utils.ZFileField(
                        upload_to=zango.core.storage_utils.RandomUniqueFileName,
                        validators=[zango.core.storage_utils.validate_file_extension],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "email",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="dynamic_models.emailmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailAlternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "alternative_body",
                    models.TextField(blank=True, verbose_name="Alternative Body"),
                ),
                (
                    "alternative_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alternative Type"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "email",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="dynamic_models.emailmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommmunicationActiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sms", models.BooleanField(default=False)),
                ("email", models.BooleanField(default=False)),
                ("imessage", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "destination_number",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Caller Number"
                    ),
                ),
                (
                    "agentId",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Agent Number"
                    ),
                ),
                (
                    "call_duration",
                    models.IntegerField(
                        null=True, verbose_name="Call Duration in Seconds"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(null=True, verbose_name="Call Start Time"),
                ),
                ("end_time", models.DateTimeField(null=True, verbose_name="End Time")),
                (
                    "call_type",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        max_length=20,
                        null=True,
                        verbose_name="Call Type",
                    ),
                ),
                (
                    "call_record_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Call Record URL(Provider Server)",
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original File Name"
                    ),
                ),
                (
                    "call_record",
                    zango.core.storage_utils.ZFileField(
                        blank=True,
                        null=True,
                        upload_to=zango.core.storage_utils.RandomUniqueFileName,
                        validators=[zango.core.storage_utils.validate_file_extension],
                        verbose_name="Call Record",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("knowlarity", "Knowlarity"),
                            ("exotel", "Exotel"),
                            ("ozonetel", "Ozonetel"),
                            ("aisth", "AIS Thailand"),
                            ("nice", "NICE"),
                        ],
                        max_length=100,
                        verbose_name="Telephony Provider",
                    ),
                ),
                (
                    "is_file_synced",
                    models.BooleanField(
                        default=False, verbose_name="Is mp3 file synced"
                    ),
                ),
                (
                    "extra_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "response_text",
                    models.TextField(null=True, verbose_name="Response Text"),
                ),
                ("call_status", models.CharField(max_length=255)),
                (
                    "agent",
                    zango.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dynamic_models.telephonyagent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_default_active_status),
    ]
