# Generated by Django 4.2.11 on 2024-04-09 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zango.apps.dynamic_models.fields
import zango.core.storage_utils


class Migration(migrations.Migration):
    dependencies = [
        ("appauth", "0006_appusermodel_app_objects"),
        ("dynamic_models", "communication_0002_notes_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmodel",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
